15

diff --git a/.github/workflows/deloy.yml b/.github/workflows/deloy.yml
--- a/.github/workflows/deloy.yml
+++ b/.github/workflows/deloy.yml
@@ -25,5 +25,9 @@ jobs:
       run: |
         for file in ${{ steps.changed-files.outputs.files }}; do
           php -l $file
+          if [ $? -ne 0 ]; then
+            echo "Syntax error in $file"
+            exit 1
+          fi
         done
       if: steps.changed-files.outputs.files != ''
